services:
  - type: web
    name: totem-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api_backend.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10
