services:
  - type: web
    name: painel-de-pedidos
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api_backend:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10
